CenterEdge/Phoenix.Spinnaker.PipelineTemplates

- configs/businessentities/businessentities-config.yml
- configs/businessentities/tempsmoketest-config.yml
Motivation
---
Now that the templates are ready, it's time to convert our pipelines to use them.
Modification
---
- Added the BusinessEntities Config
- Added the BusinessEntities Temp Smoke Test Config
https://centeredge.atlassian.net/browse/PHNX-1026
> Business Entities Pipeline Config (PHNX-1026)

- configs/pricelists/pricelists-config.yml
- configs/pricelists/tempsmoketest-config.yml
Motivation
---
Now that we have pipeline templates created, we want to update our spinnaker pipelines to use them.
Modification
---
- Added PriceLists Pipeline Config
- Added PriceLists Temp Smoke Test Pipeline Config
https://centeredge.atlassian.net/browse/PHNX-1029
> PriceLists Pipeline Config (PHNX-1029)

- configs/posdesigner/posdesigner-config.yml
- configs/posdesigner/tempsmoketest-config.yml
Motivation
---
Now that templates are ready, we want to convert our existing pipelines to use them.
Modification
---
- Added POSDesigner Pipeline Config
- Added POSDesigner Temp Smoke Test Config
https://centeredge.atlassian.net/browse/PHNX-1030
> POSDesigner Pipeline Config (PHNX-1030)

- configs/transactions/tempsmoketest-config.yml
- configs/transactions/transactions-config.yml
Motivation
---
Now that the templates are ready, it's time to convert our spinnaker pipelines to use them.
Modification
---
- Added Transactions Pipeline Config
- Added Transactions Temp Smoke Test Config
https://centeredge.atlassian.net/browse/PHNX-1027
> Transactions Pipeline Config (PHNX-1027)

- configs/authz/authorization-config.yml
- configs/authz/tempsmoketest-config.yml
- templates/production-template.yml
Motivation
---
We need to create a pipeline config for the new Authorization microservice.
Modification
---
- Added a new pipeline config for the Authorization MS
- Updated production-template to incorporate name of the MS instead of always using ...service-productcatalogs
https://centeredge.atlassian.net/browse/PHNX-1225
> Authorization Pipeline Config (PHNX-1225)

- configs/authn/authentication-config.yml
- configs/authn/tempsmoketest-config.yml
- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
The new Authentication MS needs a Pipeline Config!
Modification
---
- Updated the Templates with new ENV variables
- Added authn configs for production and smoketests
https://centeredge.atlassian.net/browse/PHNX-1234
> Add Authentication Pipeline Config (PHNX-1234)

- configs/capacityareas/capacityareas-config.yml
- configs/capacityareas/tempsmoketest-config.yml
Motivation
---
The Capacity Areas MS needs a config.
Modification
---
- Added capacityareas-config.yml
- Added tempsmoketest-config.yml
https://centeredge.atlassian.net/browse/PHNX-1265
> Capacity Areas Pipeline Config (PHNX-1265)

- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
The ENV variables used by the AuthN service were streamlined. We now only need 3 values, and the names of have been slightly changed.
Modification
---
- Removed unnecessary ENV variables for AuthN
- Changed the ENV variable names to match those in the MS
https://centeredge.atlassian.net/browse/PHNX-1270
> Update Template ENV Variables (PHNX-1270)

- configs/eventscheduling/eventscheduling-config.yml
- configs/eventscheduling/tempsmoketest-config.yml
Motivation
---
The new EventScheduling MS needs pipeline configs.
Modification
---
- Added a production config
- Added a tempsmoketest config
https://centeredge.atlassian.net/browse/PHNX-1288
> EventScheduling Config (PHNX-1288)

- configs/waivers/tempsmoketest-config.yml
- configs/waivers/waivers-config.yml
Motivation
--------------
We need to have pipeline templates for waivers
Modifications
------------------
Created them
https://centeredge.atlassian.net/browse/PHNX-1312
> Add waiver pipeline templates (PHNX-1312)

- configs/mapping/mapping-config.yml
- configs/mapping/tempsmoketest-config.yml
Motivation
----
We need to be able to deploy the mapping service through spinnaker
Modifications
----
Added the following config files:
* `config/mapping/mapping/mapping-config.yml`
* A standard config file that used the identical files in the project to make
* Adjusted variables to be specific for mapping service
* `configs/mapping/tempsmoketest-config.yml`
* A standard smoke test config gile that used the identical files in the project to make
* Adjusted variables to be specific for mapping service
Result
----
The initial spinnaker config files for Mapping should be complete
https://centeredge.atlassian.net/browse/PHNX-1473
> Added Spinnaker Config file For Mapping Service (PHNX-1473)

- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
Our new production pool requires a client secret to authenticate properly
Modifications
---
Map the k8s secret to the environment variable
https://centeredge.atlassian.net/browse/PHNX-1539
> Add Cognito clientSecret env var to templates (PHNX-1539)

- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
We have a finalized nginx proxy that does RED logging to datadog
Modifications
---
Pointed to the new proxy
https://centeredge.atlassian.net/browse/PHNX-1731
> Finalize templates with latest nginx proxy (PHNX-1731)

- configs/mashtub2/mashtub2-config.yml
- configs/mashtub2/tempsmoketest-config.yml
Motivation
---
Mashtub 2 needs pipeline configurations
Modifications
---
I made them
https://centeredge.atlassian.net/browse/PHNX-1925
> Adding pipeline configurations for Mashtub2 (PHNX-1925)

- configs/waivers/tempsmoketest-config.yml
- configs/waivers/waivers-config.yml
Motivation
----------
Need to add S3 access to the waivers bucket for the waivers service
Modifications
-------------
Add annotations for Kube2IAM
https://centeredge.atlassian.net/browse/DO-415
> Modify pipelines for S3 access to waivers (DO-415)

- templates/production-template.yml
Motivation
----------
Now that autoscaling is working set the min number of replicas to 2
Modifications
-------------
Change Min to 2
Results
-------
We will have the ability to go to 2 replicas when we have low demand
https://centeredge.atlassian.net/browse/DO-445
> Set the min number of replicas to 2 (DO-445)

- templates/cluster-cleanup-template.yml
Motivation
---
We want a cron pipeline to run every 24 hours to keep our production environment from keeping around unused, idle clusters.
The first step is to create the pipeline template.
Modification
---
- Added a new cluster-cleanup template
https://centeredge.atlassian.net/browse/PHNX-2177
> Cluster Cleanup Template (PHNX-2177)

- configs/activityscheduling/cleanup-config.yml
- configs/authn/cleanup-config.yml
- configs/authz/cleanup-config.yml
- configs/businessentities/cleanup-config.yml
- configs/employees/cleanup-config.yml
- configs/mapping/cleanup-config.yml
- configs/mashtub2/cleanup-config.yml
- configs/posdesigner/cleanup-config.yml
- configs/pricelists/cleanup-config.yml
- configs/productcatalogs/cleanup-config.yml
- configs/stations/cleanup-config.yml
- configs/transactions/cleanup-config.yml
- configs/waivers/cleanup-config.yml
Motivation
---
We want to cleanup any unused application containers overnight.
Modification
---
- Added a clean-config file to each MS
Result
---
- Each application should have unused application containers removed at 3a
https://centeredge.atlassian.net/browse/PHNX-2179
> Cleanup Configs (PHNX-2179)

- configs/onlinewaivers/onlinewaivers-config.yml
Motivation
---
The spinnaker trigger was pointing to phoenix-177420/phoenix-service-onlinewaivers
Modification
---
- Updated trigger to piont to phoenix-177420/phoenix-onlinewaivers
https://centeredge.atlassian.net/browse/PHNX-2235
> BUGFIX: Online Waivers Trigger (PHNX-2235)

- configs/pdf/cleanup-config.yml
- configs/pdf/pdf-config.yml
- configs/pdf/tempsmoketest-config.yml
- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
We need to be able to deploy the pdf service into k8s
Modifications
---
Added appropriate pipelines
https://centeredge.atlassian.net/browse/PHNX-2394
> Add Pdf service spinnaker pipelines (PHNX-2394)

- templates/production-template.yml
Motivation
------------
Waivers MS is failing because the Mappings__Host environment variable isn't set.
Modifications
Added the Mappings__Host variable, again.
https://centeredge.atlassian.net/browse/PHNX-2431
> Add Mappings host (PHNX-2431)

- templates/mt-production-template.yml
- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
The latest nginx proxy allows us to pass large files to our CSV upload which is necessary to process the existing Waiver information for existing customers.
Modification
---
- Updated production-template
- Updated tempsmoketest-template
- Updated mt-production-template
https://centeredge.atlassian.net/browse/PHNX-2593
> Update nginx proxy v9 (PHNX-2593)

- templates/mt-production-template.yml
- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
We updated our regex matching for the bulk import endpoints which should match whether or not it's production or smoke tests.
Modification
---
- Updated nginx proxy ref to 10
https://centeredge.atlassian.net/browse/PHNX-2598
> Nginx Version 10 (PHNX-2598)

- templates/mt-production-template.yml
- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
Update to nginx v11 which should be better pattern matching for bulkImport endpoints...
Modification
---
- Updated all templates to nginx-prox:v11
https://centeredge.atlassian.net/browse/PHNX-2600
> Update to Nginx v11 (PHNX-2600)

- templates/auth-production-template.yml
Motivation
---
The AuthZ service needs to be able to talk to the BE MS
Modifications
---
Update the auth-production-template to have the environment variable
https://centeredge.atlassian.net/browse/PHNX-2773
> Add BE MS Environment var to Auth template (PHNX-2773)

- templates/auth-production-template.yml
Motivation
---
Everything is broken and the building is on fire
Modifications
---
Removed errant field
https://centeredge.atlassian.net/browse/PHNX-2774
> Fix errant extra name field on env var (PHNX-2774)

- .editorconfig
- templates/advantageproxy-template.json
Motivation
----------
Implement a shared pipeline template, using MPTv2, for deploying the
Advantage Proxy to an environment.
Modifications
-------------
Created the template.
Added a .editorconfig file for editing consistency.
https://centeredge.atlassian.net/browse/ADV-14361
> Advantage Proxy pipeline template (ADV-14361)

- templates/auth-production-template.yml
- templates/mt-production-template.yml
- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
------------
We've made changes to the nginx proxy image to allow setting waiver upload limits via environment variables and need to update the image that the pipeline uses.
Modifications
Updated all uses of nginx proxy to v17 (latest).
https://centeredge.atlassian.net/browse/PHNX-2874
> Update Nginx Proxy to v17 (PHNX-2874)

- configs/activityscheduling/activityscheduling-config.yml
- configs/activityscheduling/tempsmoketest-config.yml
- configs/authn/authentication-config.yml
- configs/authn/tempsmoketest-config.yml
- configs/authz/authorization-config.yml
- configs/authz/tempsmoketest-config.yml
- configs/businessentities/businessentities-config.yml
- configs/businessentities/tempsmoketest-config.yml
- configs/employees/employees-config.yml
- configs/employees/tempsmoketest-config.yml
- configs/mapping/mapping-config.yml
- configs/mapping/tempsmoketest-config.yml
- configs/mashtub2/mashtub2-config.yml
- configs/mashtub2/tempsmoketest-config.yml
- configs/onlinewaivers/onlinewaivers-config.yml
- configs/pdf/pdf-config.yml
- configs/pdf/tempsmoketest-config.yml
- configs/posdesigner/posdesigner-config.yml
- configs/posdesigner/tempsmoketest-config.yml
- configs/pricelists/pricelists-config.yml
- configs/pricelists/tempsmoketest-config.yml
- configs/productcatalogs/productcatalogs-config.yml
- configs/productcatalogs/tempsmoketest-config.yml
- configs/stations/stations-config.yml
- configs/stations/tempsmoketest-config.yml
- configs/transactions/tempsmoketest-config.yml
- configs/transactions/transactions-config.yml
- configs/waivers/tempsmoketest-config.yml
- configs/waivers/waivers-config.yml
Motivation
---
With the new pipeline template(s) now supporting both a prod and a staging annotation variable. We want to update existing annotations with the new 'environment' k/v pair and add a definition for podAnnotationsStaging where appropriate.
Note: Not all configs will need to be updated.
Modification
---
- Updated podAnnotations with new 'environment' kv pair where appropriate
- Added podAnnotationsStaging variable definition where appropriate
https://centeredge.atlassian.net/browse/PHNX-2893
> Update Pod Annotation Definitions (PHNX-2893)

- configs/authn/emergency-config.yml
- configs/authz/emergency-config.yml
- templates/emergency-auth-production-template.yml
Motivation
---
We need emergency pipelines for the AuthN/AuthZ services
Modifications
---
Added the template and the corresponding configs
https://centeredge.atlassian.net/browse/PHNX-3363
> Add emergency pipelines for AuthN/AuthZ (PHNX-3363)

- configs/salestax/cleanup-config.yml
- configs/salestax/emergency-config.yml
- configs/salestax/pricelists-config.yml
- configs/salestax/tempsmoketest-config.yml
Motivation
----------
We have a new sales tax microservice.
https://centeredge.atlassian.net/browse/PHNX-3412
> Create template configs for sales tax svc (PHNX-3412)

- templates/mt-production-template.yml
Motivation
---
We're having stability issues on MT so we are going to use a bigger ice cube for the moment
Modifications
---
Upped the pods to 3 and the RAM to 1024-2048
https://centeredge.atlassian.net/browse/PHNX-3749
> Increase minimum MT pods and RAM (PHNX-3749)

- configs/pictures/cleanup-config.yml
- configs/pictures/emergency-config.yml
- configs/pictures/pictures-config.yml
- configs/pictures/tempsmoketest-config.yml
Motivation
----------
We have a new pictures microservice.
https://centeredge.atlassian.net/browse/PHNX-3717
> Create template configs for pictures svc (PHNX-3717)

- configs/cardprocessing/cleanup-config.yml
- configs/cardprocessing/emergency-config.yml
- configs/cardprocessing/productcatalogs-config.yml
- configs/cardprocessing/tempsmoketest-config.yml
Motivation
------------
We want to be able to process credit cards through a card processing microservice using TriPos.
Modifications
Added configs for card processing MS pipelines.
https://centeredge.atlassian.net/browse/PHNX-3616
> Add CardProcessing pipelines (PHNX-3616)

- configs/customers/cleanup-config.yml
- configs/customers/customers-config.yml
- configs/customers/emergency-config.yml
- configs/customers/tempsmoketest-config.yml
Motivation
---
We're creating a new customers microservice
Modifications
---
Added the pipeline configs
https://centeredge.atlassian.net/browse/PHNX-4177
> Added customers pipeline configs for the new MS (PHNX-4177)

- configs/cardprocessing/cardprocessing-config.yml
- configs/cardprocessing/emergency-config.yml
Motivation
---
The CardProcessing MS will oon depend on Shawarma being enabled to handle reversals automatically
Modifications
---
Enabled Shawarma on CardProcessing pipelines
https://centeredge.atlassian.net/browse/PHNX-4425
> Enabled Shawarma for CardProcessing MS (PHNX-4425)

- templates/production-template.yml
Motivation
------------
We want to actually collect money from customers using self-service kiosk.
Modifications
Added endpoint overrides for TriPos APIs
https://centeredge.atlassian.net/browse/PHNX-4616
> change TriPosCloud endpoints to production (PHNX-4616)

- configs/waivers/emergency-config.yml
- configs/waivers/waivers-config.yml
- templates/auth-production-template.yml
- templates/emergency-auth-production-template.yml
- templates/emergency-mt-production-template.yml
- templates/emergency-production-template.yml
- templates/mt-production-template.yml
- templates/onlinewaivers-prod-template.yml
- templates/production-template.yml
- templates/tempsmoketest-template.yml
Motivation
---
Update probe timeouts to 5s
Modification
---
- Updated timeouts on probes to 5s
https://centeredge.atlassian.net/browse/PHNX-4874
> Update Probe Timeouts to 5s (PHNX-4874)

- configs/employees/emergency-config.yml
- configs/employees/employees-config.yml
Motivation
---
We added Shawarma capabilities to the employees service
Modifications
---
Enabled it in the pipeline configs
https://centeredge.atlassian.net/browse/PHNX-4952
> Enable Shawarma for Employees pipelines (PHNX-4952)

- templates/cluster-cleanup-template.yml
Motivation
---
We want to scale down server groups that are no longer active.
Modification
---
- Added a scaleDownCluster stage
https://centeredge.atlassian.net/browse/PHNX-5019
> Cleanup Scale Down (PHNX-5019)

- configs/stations/emergency-config.yml
- configs/stations/stations-config.yml
Motivation
---
We added Shawarma capabilities to the stations service
Modifications
---
Enabled it in the pipeline configs
https://centeredge.atlassian.net/browse/PHNX-5036
> Enable Shawarma for Stations pipelines (PHNX-5036)

- configs/authz/authorization-config.yml
- configs/authz/emergency-config.yml
- configs/mapping/emergency-config.yml
- configs/mapping/mapping-config.yml
- configs/transactions/emergency-config.yml
- configs/transactions/transactions-config.yml
Motivation
---
AuthZ, Mappings, and Transactions have all gained Shawarma support
Modifications
---
Enabled it for the necessary pipelines
https://centeredge.atlassian.net/browse/PHNX-5091
> Added Shawarma to more services (PHNX-5091)

- configs/mashtub2/emergency-config.yml
- configs/mashtub2/mashtub2-config.yml
Motivation
---
Mashtub gained Shawarma support
Modifications
---
Enabled it for the necessary pipelines
https://centeredge.atlassian.net/browse/PHNX-5105
> Added Shawarma to Mashtub (PHNX-5105)

- templates/emergency-mt-production-template.yml
- templates/mt-production-template.yml
Motivation
---
We need to be able to enable Shawarma for MT
Modifications
---
Added proper annotations to the pipeline templates
https://centeredge.atlassian.net/browse/PHNX-5128
> Added Shawarma to MT templates (PHNX-5128)

- configs/customers/customers-config.yml
- configs/customers/emergency-config.yml
Motivation
------------
We need to add asynchronous job processing to the customers MS using Shawarma.
Modifications
Enabled Shawarma sidecar container for customers pipelines.
https://centeredge.atlassian.net/browse/PHNX-5832
> Enable Shawarma for Customers MS (PHNX-5832)

- kubernetesV2/PhoenixCleanupPipelineTemplate.json
Motivation
----
We want to have a template for cleaning up kv2 staging pods
Modifications
----
Added Kv2CleanupPipeline
Result
----
We should now have a pipeline that is capable of cleaning up kv2 staging pods
https://centeredge.atlassian.net/browse/PHNX-6286
> KV2 Cleanup Pipeline Template (PHNX-6286)

- kubernetesV2/PhoenixEmergencyPipelineTemplate.json
- kubernetesV2/PhoenixProductionPipelineTemplate.json
- kubernetesV2/PhoenixStagingPipelineTemplate.json
Motivation
----
There are missing environment settings that certain services need. In order to bring all services to the new deployment templates, we need to include them
Modifications
----
* Added missing settings and urls to production/emergency templates
* Changed the environment variable for the asp net core environment the staging template from production to staging
Result
----
Most, if not all, settings for all services should be included in the kv2 templates
https://centeredge.atlassian.net/browse/PHNX-6322
> Add Missing Settings To KV2 Production/Emegency Templates (PHNX-6322)

- kubernetesV2/PhoenixUIPipelineTemplate.json
Motivation
----
We want to deploy the online waivers service using kv2 style templates
Modifications
----
* Created Kv2 Template for online waivers
Result
----
There should now be a kv2 template for online waivers
https://centeredge.atlassian.net/browse/PHNX-6357
> Add UI Template (PHNX-6357)

- kubernetesV2/PhoenixAdvantageProxyPipelineTemplate.json
Motivation
----
We want a kv2 template and pipelines for the Advantage proxy deployments
Modifications
----
* Added initial kv2 template for Advantage Proxy
Result
----
There should be a basic kv2 template for Advantage proxy
https://centeredge.atlassian.net/browse/PHNX-6367
> Added Kv2 Template For Advantage Proxy (PHNX-6367)

- kubernetesV2/PhoenixEmergencyPipelineTemplate.json
- kubernetesV2/PhoenixProductionPipelineTemplate.json
Motivation
----------
Current timeout of 1s is way too low.
Modifications
-------------
Increase to 3 seconds, and increase liveness wait to 10s.
https://centeredge.atlassian.net/browse/PHNX-6668
> Increase health check timeouts (PHNX-6668)

- README.md
- kubernetesV2/PhoenixEmergencyPipelineTemplateV3.yaml
- kubernetesV2/PhoenixProductionPipelineTemplateV3.yaml
Motivation
--- 
We would like RED metrics tagged with the names of the pods that are handling requests
Modification
---
- Add environment variable to tag with pod names
- Update documentation
https://centeredge.atlassian.net/browse/PHNX-7034
> Tag metrics with pod names (PHNX-7034)

- kubernetesV2/PhoenixEmergencyPipelineTemplate.json
- kubernetesV2/PhoenixEmergencyPipelineTemplateV3.yaml
- kubernetesV2/PhoenixProductionPipelineTemplate.json
- kubernetesV2/PhoenixProductionPipelineTemplateV3.yaml
- kubernetesV2/PhoenixStagingPipelineTemplate.json
Motivation
----------
This version is more compatible with the new K8S Linux kernel that comes
with EKS 1.19.
Modifications
-------------
Upgrade the version in all V2 templates.
https://centeredge.atlassian.net/browse/PHNX-7040
> Upgrade to nginx-proxy 31 (PHNX-7040)

- kubernetesV2/PhoenixEmergencyPipelineTemplate.json
- kubernetesV2/PhoenixProductionPipelineTemplate.json
Motivation
--- 
Metrics weren't being tagged with pod names from the mashtub service
Modification
---
Add environment variable to tag metrics from the mashtub service
https://centeredge.atlassian.net/browse/PHNX-7060
> Tag metrics with pod_name for mashtub (PHNX-7060)

- kubernetesV2/v4/staging-ci.yaml
- kubernetesV2/v4/staging.yaml
Motivations
-----------
QA would like to be able to deploy PR builds to staging
Modifications
------------
Add a second staging pipeline that used GCR for the trigger and has a default artifact for the git repo.
https://centeredge.atlassian.net/browse/PHNX-7587
> Allow Pr Builds to be Deployed To Staging (PHNX-7587)

- README.md
- kubernetesV2/v4/emergency.yaml
- kubernetesV2/v4/production.yaml
Motivation
---
Some clarification
Modification
---
- The angle bracket stuff in markdown wasn't visible in "preview" modes, so make them visible
- Add comments about triggers in relation to not including them in the templates
https://centeredge.atlassian.net/browse/PHNX-8283
> Update readme and add comment about triggers (PHNX-8283)
