templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
---
The Transactions microservice needs to reference ProductCatalogs__Host and the temporary smoke test template was missing a definition for BusinessEntities__Host causing it to error out.
Modifications
---
- Added ProductCatalogs__Host to Production Template
- Added ProductCatalogs__Host to Smoke Test template
- Added BusinessEntities__Host to Smoke Test template
https://centeredge.atlassian.net/browse/PHNX-1074
=> Update Environment Hosts (PHNX-1074)

templates/production-template.yml
Motivation
---
The presence of the API_GATEWAY_KEY in the Production cluster definition prevented the microservices from communicating with each other.
Modifications
---
- Removed API_GATEWAY_KEY from the Production cluster definition
https://centeredge.atlassian.net/browse/PHNX-1081
=> Remove API_GATEWAY_KEY (PHNX-1081)

configs/productcatalogs/productcatalogs-config.yml, configs/productcatalogs/tempsmoketest-config.yml
Motivation
---
We want to convert all the spinnaker pipelines to using templates.
Modification
---
- Added Product Catalogs pipeline config
- Added Product Catalogs temp smoke test config
https://centeredge.atlassian.net/browse/PHNX-1028
=> Product Catalogs Pipeline Config (PHNX-1028)

configs/businessentities/businessentities-config.yml
Motivation
---
The BE Config had the wrong name for the Smoke Test project which caused them to not run when the pipeline executed.
Modification
---
- Renamed the Smoke Test project to Phoenix.Service.BusinessEntities.Smoke
https://centeredge.atlassian.net/browse/PHNX-1089
=> BE Config Wrong Smoke Test Name (PHNX-1089)

configs/posdesigner/posdesigner-config.yml, configs/pricelists/pricelists-config.yml, configs/productcatalogs/productcatalogs-config.yml, configs/transactions/transactions-config.yml
Motivation
---
There's been inconsistency in the naming of our Smoke Test projects.
Sometimes it's:
Phoenix.Service.{Servicename}.Smoke
other times it's:
Phoenix.Service.{ServiceName}.Tests.Smoke
Pipeline Smoke Test project names were recently updated to made consistent.
The pipeline template configs for all the microservice pipelines should be updated to
Phoenix.Service.[ServiceName].Smoke
Modification
---
- Changed the smoketestjob parameter for all pipeline configs to point to the correctly named project
https://centeredge.atlassian.net/browse/PHNX-1093
=> Update Smoke Test Names (PHNX-1093)

templates/production-template.yml
Motivation
---
A change was made to our ngninx-proxy image to fix a bug. In order to incorporate that into our microservices, we need to update the production template to reference the new version.
Modification
---
- Updated the ngnix-proxy images to use version 4
https://centeredge.atlassian.net/browse/PHNX-1129
=> Update Nginx Proxy to Version 4 (PHNX-1129)

templates/production-template.yml
Motivation
---
Apparently the "tag" field in the imageDescription block of the template controls which version of an image is pulled down from gcr regardless of which version is specified in the imageId field.
Modification
---
- Updated the nginx proxy imageDescription "tag" field to the value "4"
https://centeredge.atlassian.net/browse/PHNX-1130
=> Update Template Tag to 4 (PHNX-1130)

templates/tempsmoketest-template.yml
Motivation
---
The Temp Smoke Test template was still using the old nginx-proxy:2
Modification
---
- Updated to nginx-proxy:4
https://centeredge.atlassian.net/browse/PHNX-1271
=> Update nginx-proxy to version 4 (PHNX-1271)

configs/stations/stations-config.yml, configs/stations/tempsmoketest-config.yml
Motivation
---
Stations MS needs pipelines for production and smoke tests.
Modification
---
- Added stations-config.yml
- Added tempsmoketest-config.yml for Stations
https://centeredge.atlassian.net/browse/PHNX-1291
=> Stations Config (PHNX-1291)

templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
---
After confirming the buffer overflow fix, it was applied to the NginxProxy project and deployed. That fix is contained in version 7 of that project and should be rolled out to production.
Modification
---
- Set all references of nginx-proxy to version 7
https://centeredge.atlassian.net/browse/PHNX-1332
=> Update Templates to NginxProxy 7 (PHNX-1332)

configs/activityscheduling/activityscheduling-config.yml, configs/activityscheduling/tempsmoketest-config.yml
Motivation
--------------
In the domain we determined that "Activity" was a better name that "Event"
Modifications
------------------
Add configs for activities service
https://centeredge.atlassian.net/browse/PHNX-1279
=> Add activity scheduling service (PHNX-1279)

configs/authn/authentication-config.yml, templates/production-template.yml
Motivation
---
We need to be able to specify the AWS role used for a pod
Modifications
---
Added a new "awsrole" variable to the template.  Implemented its usage for AuthN
https://centeredge.atlassian.net/browse/PHNX-1465
=> Add AWS Role variable to pod annotations (PHNX-1465)

templates/production-template.yml
Motivation
---
Spinnaker pipelines are failing.
Modifications
---
Switched from using an awsrole var to using a podAnnotations var that defaults to an empty object
https://centeredge.atlassian.net/browse/PHNX-1471
=> Change to using podAnnoationsVar (PHNX-1471)

configs/authn/authentication-config.yml, templates/tempsmoketest-template.yml
Motivation
---
We need to add an aws role pod annotation to the AuthN service
Modifications
---
Added the podAnnotations variable to the smoketest template. Added the role pod annotations to the AuthN config
https://centeredge.atlassian.net/browse/PHNX-1471
=> Configure podAnnotations for AuthN (PHNX-1471)

configs/authn/tempsmoketest-config.yml
Motivation
---
We need to add an aws role pod annotation to the AuthN smoke test pipeline
Modifications
---
Added the podAnnotations variable to the smoketest pipeline
https://centeredge.atlassian.net/browse/PHNX-1471
=> Configure podAnnotations for AuthN smoke (PHNX-1471)

templates/tempsmoketest-template.yml
Motivation
---
We want to have a default temporary password for smoke tests so we can test user creation and password reset
Modifications
---
Add the secret->env var mapping
https://centeredge.atlassian.net/browse/PHNX-1540
=> Add Cognito default temp pass env var to smokes (PHNX-1540)

templates/production-template.yml
Motivation
---
COGNITO_ClientId was missing from the declaration for the production cluster causing authentication to fail in production.
Modification
---
- Added COGNITO_ClientId to the production cluster declaration
https://centeredge.atlassian.net/browse/PHNX-1551
=> Added COGNITO_ClientId to Production Cluster (PHNX-1551)

templates/production-template.yml
Motivation
---
We'd like to start capturing deployment metrics. In order to do that, we've introduced a webhook into Spinnaker that feeds Datadog. The pipelines need to be updated with stages that feed data into the webhook so Datadog can start capturing metrics.
Modification
---
- Added three new stages to the template
- One stage when deployment starts
- One stage when deployment succeeds
- One stage when deployment fails
https://centeredge.atlassian.net/browse/PHNX-1556
=> Pipeline Event Notifications (PHNX-1556)

templates/production-template.yml
Motivation
---
When attempting to add new event logging to our pipelines, we adjusted the type name from datadogEvent to a more generic name of pipelineEvent.
Apparently that breaks things.
Modification
---
- Changed type from pipelineEvent to datadogEvent
https://centeredge.atlassian.net/browse/PHNX-1561
=> BUGFIX: Change stage type to datadogEvent (PHNX-1561)

templates/production-template.yml
Motivation
---
With no upper limits specific, our pods were abusing AWS and allowed to run amok. We should get them under control.
I did not add limits to our Staging pods as those are short-lived.
Credit to @mmmasent for initial research and implementation.
Modification
---
- Added pod limits for CPU and Memory
- Added request limits for CPU and Memory
- Parameterized the limit values with default values which can be overriden in config files
https://centeredge.atlassian.net/browse/PHNX-1542
=> Memory and CPU Limits for Pods (PHNX-1542)

templates/production-template.yml
Motivation
---
Spinnaker builds were failing while parsing the memory limits with lower case 'mi'
Modification
---
- Updated suffix to 'Mi' based on Kubernetes documentation
https://centeredge.atlassian.net/browse/PHNX-1592
=> Change Memory Suffix from 'mi' to 'Mi' (PHNX-1592)

templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
---
We want to be able to do RED monitoring of all of our microservices
Modifications
---
Updated to a CI version of the nginx proxy that has statd baked in that does request logging into datadog.  Added necessary environment variables
https://centeredge.atlassian.net/browse/PHNX-1725
=> Changed to StatsD version of nginx proxy (PHNX-1725)

templates/production-template.yml
Motivation
----------
Currently we are retaining 3 deployments which is more than
necessary at this point in time. Reducing it to 2 will still
allow us to rollback to the previous version if required.
Modifications
-------------
Change the definition in the Shrink Cluster stage
https://centeredge.atlassian.net/browse/DO-357
=> Change the number of retained deployments (DO-357)

templates/tempsmoketest-template.yml
Motivation
---
Adding a variable for the image tag seems to have broken things for Spinnaker. We should remove it.
Modification
---
- Removed the offending variable gcrimagetag
https://centeredge.atlassian.net/browse/PHNX-1899
=> Remove gcrimagetag variable (PHNX-1899)

configs/mashtub2/mashtub2-config.yml
Motivation
---
We need to be able to run smoketests with the appropriate sdk version in spinnaker/jenkins
Modifications
---
Update the pipeline config to query the sdk version and pass it to the jenkins job
https://centeredge.atlassian.net/browse/PHNX-2155
=> Update pipeline to run smoketests (PHNX-2155)

templates/production-template.yml
Motivation
----------
Horizontal pod autoscaling is not working correctly dur to the fact that
requests and limits have not been set on the nginx sidecars. This data is
required for the stats to be reported and used.
Modifications
-------------
Added requests and limits for nginx
Results
-------
Stats are returned.
https://centeredge.atlassian.net/browse/DO-445
=> Add requests and limits for nginx (DO-445)

templates/cluster-cleanup-template.yml
Motivation
---
The cleanup template wasn't checking if some of the temp or staging application clusters existed or not before trying to remove them. That should now be fixed.
Modification
---
- Added findImage from cluster stage before trying to remove the temp cluster
- Added findImage from cluster stage before trying to remove the staging cluster
- Failed findImage stages halt the execution branch, but not the pipeline
- Updated the cron trigger so it's daily at 3am
https://centeredge.atlassian.net/browse/PHNX-2180
=> More Robust Pipeline Cluster Cleanup Template (PHNX-2180)

templates/mt-production-template.yml
Motivation
----------
The Mashtub pipeline needed the same min/desired number and the
requests and limits put on the production template
Modifications
-------------
Changed the min and desired number of instances to 2
Added requests and limits to the nginx container.
Results
-------
The pods are deployed as expected.
https://centeredge.atlassian.net/browse/DO-445
=> Fix Mashtub template for size and qty (DO-445)

templates/cluster-cleanup-template.yml, templates/mt-production-template.yml, templates/production-template.yml
Motivation
---
Too many alerts when running cleanup pipelines. Not enough alerts when Smoke Tests fail (as in no alerts are sent...)
Modification
---
- Only send alerts when cleanup pipelines fail
- Start sending alerts when Smoke Test stages fail in production
https://centeredge.atlassian.net/browse/PHNX-2236
=> Adjust Alerts (PHNX-2236)

templates/mt-production-template.yml, templates/production-template.yml
Motivation
---
Currently when Smoke Tests fail, the pipeline still completes successful without an error notification. We'd like the pipeline to send a fail notification when the smoke test stage fails.
Modification
---
- Added a new Stage that checks for Smoke Test Failures after all cleanup has completed
- If Smoke Tests fail, the pipeline fails
https://centeredge.atlassian.net/browse/PHNX-2271
=> Fail Pipeline When Smoke Tests Fail (PHNX-2271)

templates/mt-production-template.yml, templates/production-template.yml
Motivation
---
The final stage that checks for smoke test failures is returning a false positive on successful runs of the smoke tests.
Modification
---
- Updated the stage that fails the pipeline so it's only enabled when the smoke test stage fails
- Dump the output of the smoke test stage build result so it's in the JSON source in spinnaker
https://centeredge.atlassian.net/browse/PHNX-2282
=> BUGFIX False Smoke Test Fail Check (PHNX-2282)

templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
Importing waivers from Webstore 2 will require getting the SiteId for a business entity from the Mappings service and we need to add the mappings load balancer to an environment variable in the deployment pipelines used by Spinnaker.
Modifications
Added environment variables to the production and smoke test pipeline templates for the mapping service api.
https://centeredge.atlassian.net/browse/PHNX-2414
=> Add Mappings API environment variables (PHNX-2414)

templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
---
Loggly indicates the value 100 is invalid as a sample rate. Datadog documentation shows 50% sampling would be 0.5 - so sampling 100% should probably use the value 1
https://docs.datadoghq.com/developers/faq/dog-statsd-sample-rate-parameter-explained/
Modification
---
- Set the statsD default sample rate to 1
https://centeredge.atlassian.net/browse/PHNX-2603
=> StatsD Sample Rate 1 (PHNX-2603)

configs/businessentities/businessentities-config.yml, configs/businessentities/tempsmoketest-config.yml
Motivation
------------
Business Entity microservice pods need a special annotation to allow them to assume a role which gives them access to S3 buckets.
Modifications
Added pod annotations for Business Entities service to have IAM roles.
https://centeredge.atlassian.net/browse/PHNX-2618
=> Add Business Entity Service pod annotations (PHNX-2618)

templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
Updates have been made to the nginx proxy image to fix 415 errors when uploading waiver import CSVs and the spinnaker pipeline needs to be updated to use the new nginx proxy image.
Modifications
Updated Nginx Proxy version to v12.
https://centeredge.atlassian.net/browse/PHNX-2621
=> Update Nginx Proxy image to v12 (PHNX-2621)

templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
Nginx proxy has been updated to fix issues with bulk waiver imports and spinnaker pipelines need to be updated to use the new image.
Modifications
Updated the Nginx proxy version to v13.
https://centeredge.atlassian.net/browse/PHNX-2622
=> Update nginx proxy to v13 (PHNX-2622)

templates/mt-production-template.yml, templates/tempsmoketest-template.yml
Motivation
---
We need to be able to pass the k8s Jwt secret into the environment variables for MT2
Modifications
---
Added the environment variable mapping configuration to the MT template and the temp smoke tests template
https://centeredge.atlassian.net/browse/PHNX-2643
=> Added JwtOptions Secret to Templates (PHNX-2643)

templates/mt-production-template.yml
Motivation
----
RabbitMQ is now being used by MashTub and needs config settings for it to properly work as intended
Modifications
----
Added RabbitMQ settings for the following template:
* `templates/mt-production-template.yml`
Result
----
The MashTub Spinnaker pipeline should now have settings for RabbitMQ
https://centeredge.atlassian.net/browse/PHNX-2646
=> Updated MashTub Template to include RabbitMQ config settings(PHNX-2646)

configs/auth/auth-config.yml, configs/auth/cleanup-config.yml, configs/auth/tempsmoketest-config.yml, templates/auth-production-template.yml
Motivation
---
The new auth service requires its own spinnaker pipeline template that gives it access to both the jwt secret and cognito
Modifications
---
Created a new pipeline template for the unified auth service. Added pipelines for the auth service
https://centeredge.atlassian.net/browse/PHNX-2706
=> Add pipeline and template for new auth service (PHNX-2706)

configs/mashtub2/mashtub2-config.yml, templates/mt-production-template.yml
Motivation
------------
The FindImage stage of the MashTub production pipeline is currently looking for images of MT1 instead of MT2 which causes the current build number to be reported incorrectly for use in smoke tests.
Modifications
- Changed the pipeline template to look for MT2 images.
- Updated smoketestjob in the MT2 config to reflect a change made in Jenkins to the Job type for the smoke test job
https://centeredge.atlassian.net/browse/PHNX-2720
=> Update MT Production template to find MT2 image (PHNX-2720)

configs/mashtub2/mashtub2-config.yml
Motivation
---
We were originally requesting 1/100th a CPU for Mashtub2 and felt that was probably too light based on the amount of scaling we're seeing in MT2 over the weekends.
Recommendation was to bump to 1/4th and 1/2th for request and limit respectively.
Modification
---
- Bumped the cpu request to 250m
- Bumped the cpu max to 500m
https://centeredge.atlassian.net/browse/PHNX-2733
=> Bump MT2 CPU Limits (PHNX-2733)

templates/auth-production-template.yml, templates/production-template.yml
Motivation
---
The Auth MS template is missing the couchbase server url and the standard template has extraneous cognito variables
Modifications
---
Added the CB env var to the auth template production deploy and removed the cognito vars from the standard template production deploy (both were already done for smoke tests)
https://centeredge.atlassian.net/browse/PHNX-2776
=> Fix environment vars for MS templates (PHNX-2776)

configs/authz/authorization-config.yml, configs/authz/tempsmoketest-config.yml
Motivation
------------
We recently added some Cognito calls to the AuthZ microservice, but they aren't working in production due to the lack of AWS credentials on AuthZ pods.
Modifications
Added pod annotations for authZ pods to be able to access AWS Cognito service.
https://centeredge.atlassian.net/browse/PHNX-2784
=> Add AWS Pod annotations for AuthZ (PHNX-2784)

templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
Some waiver CSV uploads may take a long time to complete and we need to set a timeout which is long enough to allow them to finish.
Modifications
Set environment variable for waiver upload timeout which pulls its value from a k8s config map.
https://centeredge.atlassian.net/browse/PHNX-2855
=> Update templates to set waiver upload timeout variable (PHNX-2855)

templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
Some waiver CSV uploads may take a long time and we need a way to configure longer timeouts for those endpoints.
Modifications
Updated nginx proxy to version 14 which has timeout settings for waiver upload endpoints based on environment variables.
https://centeredge.atlassian.net/browse/PHNX-2818
=> Update Nginx proxy to apply waiver upload timeouts (PHNX-2818)

templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
YAML is picky about spacing and the name property is indented too far for `WaiverUploadOptions__KeepAliveTimeout`.
Modifications
Removed 10 spaces.
https://centeredge.atlassian.net/browse/PHNX-2867
=> Fix spacing of environment variable names for timeouts (PHNX-2867)

templates/auth-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
We want to be able to change the size of the request limit for waiver uploads without needing to rebuild our nginx proxy image every time.
Modifications
- Renamed waiver-upload-timeout configmap to waiver-upload-options to reflect changes in the name of the configmap.
- Added missing timeout environment variable to nginx proxy.
- Added request size limit environment variable to nginx proxy.
https://centeredge.atlassian.net/browse/PHNX-2872
=> Add max request size environment variable (PHNX-2872)

templates/auth-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
Nginx proxy v17 image was broken and not properly substituting waiver upload option environment variables.
Modifications
Updated all nginx-proxy references to v18.
https://centeredge.atlassian.net/browse/PHNX-2876
=> Update to nginx proxy v18 (PHNX-2876)

templates/auth-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml
Motivation
---
To better monitor and filter our pods, we're adding a new podAnnotationsStaging variable so we can better distinguish between staging and production pods in Datadog.
This is the first of a multi-step process for getting the new variable into use.
Modification
---
- Added a new podAnnotationsStaging variable
https://centeredge.atlassian.net/browse/PHNX-2892
=> Add podAnnotationsStaging Variable (PHNX-2892)

templates/auth-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
----------
Current values in DataDog are being scaled by 100x.
Modification
------------
Change to build 19 of the Nginx proxy.
https://centeredge.atlassian.net/browse/PHNX-2926
=> Use Nginx proxy with correct StatsD rate (PHNX-2926)

templates/auth-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
----------
The StatsD rate should be 100 to log 100% by default, not 1 for 1%.
Especially since at low request volumes this skews values significantly.
https://centeredge.atlassian.net/browse/PHNX-2926
=> Correct default StatsD rate (PHNX-2926)

templates/auth-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml
Motivation
---
Now that all the configs have a value set for the new podAnnotationsStaging variable, it's time to put that variable to use.
Modification
---
- Actually use the podAnnotationsStaging variable in the staging stages
https://centeredge.atlassian.net/browse/PHNX-2894
=> Use podAnnotationsStaging Variable (PHNX-2894)

templates/auth-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
Our Nginx proxy is currently logging every 2xx/3xx response to the console which is overflowing our limits in loggly.  We need to update this to exclude successful requests.
Modifications
Updated nginx-proxy image to v23 which only logs non-success status codes.
https://centeredge.atlassian.net/browse/PHNX-2956
=> Update nginx proxy to only log non-success status (PHNX-2956)

configs/waivers/waivers-config.yml, templates/production-template.yml
Motivation
----
* There are new environment variables for the waiver service:
* `Statsd__Enabled`
* `Statsd__Config__StatsdServerName`
* We need to set those values for the spinnaker pipeline
Modifications
----
* Updated production template to include the new fields and values
* Updated the waiver config to include the new fields and values
Note: The variable names were taken from the new setting values for the RED Metric update in waiver service, found here: https://github.com/CenterEdge/Phoenix.Service.Waivers/pull/99
Result
----
The environment variables should be applied to the new waiver service RED Metric updates when it is deployed
https://centeredge.atlassian.net/browse/PHNX-3010
=> Added StatsD Metric Variables For RED Metrics In Waiver Svc (PHNX-3010)

configs/waivers/waivers-config.yml
Motivation
------------
The current Waivers pipeline does not automatiaclly reduce the size of the `waivers-jobs-api` cluster, which results in excess server groups being left running in that cluster after each deployment.
Modifications
Added a step to the Waivers pipeline to shrink the jobs cluster after disabling the old server group.
https://centeredge.atlassian.net/browse/PHNX-3017
=> Shrink jobs cluster after deployment (PHNX-3017)

configs/waivers/waivers-config.yml, templates/production-template.yml
Motivation
----------
Use a single variable on the pipeline template to apply the Shawarma
annotations to deployed pods.
Modifications
-------------
Added "shawarmaEnabled" and "shawarmaStaging" variables to the
microservice template, which automatically adds the annotations.
Set the Waivers microservice to have Shawarma enabled, and also updated
the special configuration for the Jobs processor to apply the Shawarma
annotation.
https://centeredge.atlassian.net/browse/ARCH-56
=> Add Shawarma support to microservices (ARCH-56)

templates/mt-production-template.yml
Motivation
------------
We want RED metrics reported for MashTub requests.
Modifications
Added required StatsD configuration environment variables to enable StatsD reporting in MashTub.
https://centeredge.atlassian.net/browse/PHNX-3144
=> Add StatsD config to MashTub pipeline (PHNX-3144)

templates/auth-production-template.yml
Motivation
------------
We want to have metrics enabled for AuthN/AuthZ services.
Modifications
Set StatsD environment variables in AuthN/AuthZ pipeline.
https://centeredge.atlassian.net/browse/PHNX-3222
=> Enable StatsD for auth pipelines (PHNX-3222)

templates/auth-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
Kubernetes will only restart a pod which is failing the liveness probe, and not a pod which is failing the readiness probe.  We currently have the liveness probes configured to hit `/health` where the readiness probes hit `/health?type=ready`.  The `/health` endpoint does not attempt to retrieve a document from couchbase and will pass even when couchbase cannot be accessed which leaves us with pods that cannot process any real requests.
Modifications
Changed all templates liveness probes to use `/health?type=ready` to check for liveness.
https://centeredge.atlassian.net/browse/PHNX-3284
=> Update liveness probes to use ready checks (PHNX-3284)

templates/mt-production-template.yml
Motivation
---
We figured out the performance problem on MT, so we no longer need increased provisioning
Modifications
---
Reverted previous commit
https://centeredge.atlassian.net/browse/PHNX-3764
=> Revert "Increase minimum MT pods and RAM" (PHNX-3764)

templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
We need to be able to tell the card processing microservice where to connect when checking if a station exists.
Modifications
Added Stations__Host environment variable to configure stations host based on the K8s `stations-api` config map.
https://centeredge.atlassian.net/browse/PHNX-3876
=> Add Stations host environment variable (PHNX-3876)

templates/cluster-cleanup-template.yml
Motivation
---
The cleanup script was not leaving a rollback cluster when running overnight which could compromise our ability to quickly respond to production issues related to a bad deployment.
Modification
---
- Adjust property shrinkToSize: 2
https://centeredge.atlassian.net/browse/PHNX-2460
=> Cleanup Shrinks Down to 2 (PHNX-2460)

templates/auth-production-template.yml, templates/emergency-auth-production-template.yml, templates/emergency-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
To prevent K8s upgrades from causing downtime related to couchbase, we want to use DNS discovery in all of our microservices.
Modifications
Updated templates to provide the connection string property in the couchbase-primary k8s secret.
https://centeredge.atlassian.net/browse/PHNX-4572
=> Update spinnaker pipelines to use CB ConnectionString (PHNX-4572)

templates/production-template.yml
Motivation
------------
The TriPos transactions API client includes the /api/ section of the path in the client itself, so it should not be included in the path set in the environment variable in the spinnaker pipeline.
Modifications
Removed /api/ from the TriPos Transactions Host path
https://centeredge.atlassian.net/browse/PHNX-4626
=> Remove /api/ from TriPos Transactions host path (PHNX-4626)

configs/waivers/emergency-config.yml, configs/waivers/waivers-config.yml, templates/auth-production-template.yml, templates/emergency-auth-production-template.yml, templates/emergency-mt-production-template.yml, templates/emergency-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
We've updated the Nginx proxy docker image to raise the error_log level from info to notice and we need to update spinnaker pipelines to make use of that new image.
Modifications
Updated all templates and configs to use nginx proxy v25 docker image
https://centeredge.atlassian.net/browse/PHNX-4676
=> Update Nginx proxy to v25 (PHNX-4676)

configs/waivers/emergency-config.yml, configs/waivers/waivers-config.yml, templates/auth-production-template.yml, templates/emergency-auth-production-template.yml, templates/emergency-mt-production-template.yml, templates/emergency-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml
Motivation
------------
V25 of nginx proxy was broken due to improper encoding of nginx.conf file, so we need to replace with the fixed nginx proxy image (V26).
Modifications
Updated all nginx proxy images to V26.
https://centeredge.atlassian.net/browse/PHNX-4682
=> Update to v26 of nginx proxy (PHNX-4682)

configs/waivers/emergency-config.yml, configs/waivers/waivers-config.yml
Motivation
------------
Previously, all microservices were updated to use DnsDiscovery with the SRV record that Tom created for our couchbase cluster to prevent outages during k8s upgrades, however, the Waivers MS job pods were not updated in the config.  We want those pods to use the SRV record too.
Modifications
Updated Waivers job pods config to use SRV records for couchbase.
https://centeredge.atlassian.net/browse/PHNX-4678
=> Update Waivers job pods to use SRV record (PHNX-4678)

configs/waivers/emergency-config.yml, configs/waivers/waivers-config.yml
Motivation
---
Since the waiver jobs pods override the environment variables, it doesn't inherit the LD key
Modifications
---
Added the LD key specifically to the waiver jobs pods
https://centeredge.atlassian.net/browse/PHNX-4939
=> Added launch darkly key to waiver jobs pods (PHNX-4939)

configs/waivers/emergency-config.yml, configs/waivers/waivers-config.yml, templates/auth-production-template.yml, templates/emergency-auth-production-template.yml, templates/emergency-mt-production-template.yml, templates/emergency-production-template.yml, templates/mt-production-template.yml, templates/production-template.yml, templates/tempsmoketest-template.yml, v2/templates/PhoenixEmergencyPipelineTemplate.json, v2/templates/PhoenixProductionPipelineTemplate.json, v2/templates/PhoenixSmokeTestPipelineTemplate.json
Motivation
------------
We want separate environment variables to configure keepalive timeouts and connect/read/send timeouts.
Modifications
- Updated Nginx Proxy to v27
- Updated pipeline configs to set separate environment variables for connect/read/send/keepalive timeouts
https://centeredge.atlassian.net/browse/PHNX-4961
=> Use separate env vars for timeouts (PHNX-4961)

templates/emergency-production-template.yml, templates/production-template.yml
Motivation
------------
We need to be able to specify the timeout for the AWS client separately from the keepalive timeout used by Kestrel in the Waivers MS.
Modifications
Added `TimeoutOptions__WaiverUploadTimeout` variable to MS pipelines.
https://centeredge.atlassian.net/browse/PHNX-5005
=> Add WaiverUploadTimeout environment variable (PHNX-5005)

templates/cluster-cleanup-template.yml
Motivation
---
The cleanup pipeline template had an empty array for namespaces in two of the stages which spinnaker did not like at all.
Modification
---
- Added the namespace default to both stages where it was missing to make spinnaker happy
https://centeredge.atlassian.net/browse/PHNX-5024
=> Add Missing Namespaces (PHNX-5024)

v2/README.md, v2/templates/PhoenixSmokeTestPipelineTemplate.json
Motivation
----
* QA wants to use a version tag different from latest
Modifications
----
* Added optional variable to use a different version other than latest
* Added a brief readme to hopefully help with future updates
Result
----
QA should now be able to deploy a smoke test pipeline with any real version number
https://centeredge.atlassian.net/browse/PHNX-5141
=> Added A Version Tag For GCR Image For V2 Smoke Test Pipeline(PHNX-5141)

v2/templates/PhoenixEmergencyPipelineTemplate.json, v2/templates/PhoenixProductionPipelineTemplate.json
Motivation
----
* There is a new html service being used by V2 Template pipelines that needs production settings passed into the running containers in production
* There is a missing smoke test failure check on the production deployment phase of the normal v2 production pipelines allowing deployments of failing builds
Modifications
----
* Updated:
* `PhoenixEmergencyPipelineTemplate` - now includes html settings
* `PhoenixProductionPipelineTemplate` - now includes html settings; stops production deployments on smoke test failures
Result
----
When V2 templated pipelines are configured or reconfigured, they will contain the new updated settings
https://centeredge.atlassian.net/browse/PHNX-5498
=> Update V2 Templates For Html Settings And Smoke Test (PHNX-5498)

v2/templates/PhoenixProductionPipelineTemplate.json
Motivation
----
* Smoke tests passed but builds failed... due to a Typo
Modifications
----
* Updated template to fix typo so pipelines could find correct stage for smoke tests
Result
----
Production pipelines no longer fail despite successful smoke tests
https://centeredge.atlassian.net/browse/PHNX-5502
=> Fix Conditional Expression Typo For SmokeTests (PHNX-5502)

v2/templates/PhoenixSmokeTestPipelineTemplate.json
Motivation
----
* A new setting is required for a v2 templated service and that value was not set on the smoke test pipeline template for use causing testing issues
Modifications
----
* Added new setting to v2 spinnaker smoke test pipeline template
Result
----
QA tests should no longer fail due to a missing setting
https://centeredge.atlassian.net/browse/PHNX-5709
=> Add missing PDF setting to V2 Smoke test pipeline template (PHNX-5709)

configs/businessentities/businessentities-config.yml, configs/businessentities/emergency-config.yml, templates/emergency-production-template.yml, templates/production-template.yml
Motivation
------------
We had an outage of the business entities microservice due to out of memory conditions causing the pods to be killed by k8s.  We increased the memory limits in production to get things back up and running and we need to put those changes in source control now.  We also want to remove the nginx proxy container from production as it is no longer needed.
Modifications
- Increased memory limits in business entities config
- Removed nginx proxy container from producution pipelines
https://centeredge.atlassian.net/browse/PHNX-6016
=> Increase memory limits for business entities (PHNX-6016)

templates/advantageproxy-template.json
Motivation
----------
Add rules for forwarding traffic to QA sites via QA relay.
Modifications
-------------
Use a ConfigMap for advantageproxy environment variables, and add the
vars required for QA relay forwarding.
https://centeredge.atlassian.net/browse/STAGE-4892
=> Get advantageproxy config from ConfigMap (STAGE-4892)

kubernetesV2/PhoenixEmergencyPipelineTemplate.json
Motivation
----
The stage for deploying job pods is currently checking if smoke tests have succeeded but the emergency pipeline does not care about smoke tests
Modifications
----
Set the stage to deploy baed solely whether job pods are enabled
Result
----
Job pods should now deploy without a care for smoke tests
https://centeredge.atlassian.net/browse/PHNX-6330
=> Fix Typo In Emergency KV2 Template (PHNX-6330)

kubernetesV2/PhoenixEmergencyPipelineTemplate.json, kubernetesV2/PhoenixProductionPipelineTemplate.json, kubernetesV2/PhoenixStagingPipelineTemplate.json
Motivation
----
All of the stages are currently setting the process jobs setting to false and we should be turning on the process job settings for jobs and staging clusters (for tests)
Modifications
----
* Adjusted Production/Emergency/Staging templates so that process bulk job is:
* `ON` for staging clusters
* `ON` for jobs clusters
Result
----
Process bulk job setting should now be on only for staging and jobs clusters and off for prod clusters
https://centeredge.atlassian.net/browse/PHNX-6332
=> Adjust Job Settings For KV2 Templates (PHNX-6332)

kubernetesV2/PhoenixStagingPipelineTemplate.json
Motivation
----
The manual staging is set to be auto triggered when it should be a manual one and it is missing the iam role
Modifications
----
* Turn off the automated trigger so only a human click can turn it on
* Apply IAM Role For Staging
Result
----
Manual Staging should not auto deploy on new builds
https://centeredge.atlassian.net/browse/PHNX-6333
=> Fix Automated Trigger & IAM For Manual Staging KV2 Template(PHNX-6333)

kubernetesV2/PhoenixProductionPipelineTemplate.json
Motivation
----
The main production template is missing the auth variables for the prod stage and it isn't getting the proper settings
Modifications
----
* Add the auth variables to the prod stage of the production template
Result
----
Auth variables should be applied to service pods for prod stage
https://centeredge.atlassian.net/browse/PHNX-6340
=> Add Auth Variables For Production Template (PHNX-6340)

kubernetesV2/PhoenixEmergencyPipelineTemplate.json, kubernetesV2/PhoenixProductionPipelineTemplate.json, kubernetesV2/PhoenixUIPipelineTemplate.json
Motivation
----
* We want to autoscale pods based on a custom input than the standard 2-9 min/max pods
* MashTub needs a specific url for smoke tests to hit (passed as a job parameter)
* Smoke test nestedDirectory variable to handle the difference between pathing for services/mashtub
Modifications
----
* Added min/max pods variables for autoscaling (production, emergency production, UI pipeline templates)
* Added smokeTestUrl parameter for jenkins smoke test job
* Added directory variable to allow support for different pathing for mashtub/service jenkins jobs
Result
----
* Autoscaling should be more flexible to what a pipeline needs
* Smoke tests should work for MashTub
* Both MashTub/Services are supported by template despite pathing differences in jenkins jobs …
=> Update Templates For MT/Auto Scaling And Smoke Tests (PHNX-6363)

kubernetesV2/PhoenixProductionPipelineTemplate.json
Motivation
----------
In some cases the automatic build of the smoke test job name doesn't
work, especially related to capitalization.
Modifications
-------------
Add a template variable which can override with the full job name,
replacing the automatic job name build. If not present, defaults to
the automatic behavior.
https://centeredge.atlassian.net/browse/PHNX-6617
=> Add smoke test job override for prod deploy (PHNX-6617)

kubernetesV2/PhoenixProductionPipelineTemplate.json
Motivation
----
Some recent template changes broke spinnaker pipelines for production due to breaking nested job directories
Modifications
----
* Adjusted the logic for nested job directories to account for the recent changes
* Adjusted logic for smokeTestFullJobName to check a `-` character for using the default parse mechanism since a default empty string will cause Spinnaker UI to yell at a user if it is empty
Result
----
Production pipelines based off the production kv2 template should now work with nested job directories
https://centeredge.atlassian.net/browse/PHNX-6628
=> Adjust Kv2 Production Template To Work With Nested Jobs (PHNX-6628)

kubernetesV2/PhoenixProductionPipelineTemplate.json
Motivation
----
An earlier change removed the addition of the job directory name for a conditional branch, but it is needed and should have remained
Modifications
----
* Append the job directory field name for the logic branch
Result
----
The template should work again for the specific logic branch triggered
https://centeredge.atlassian.net/browse/PHNX-6640
=> Append Job Directory Field Name For Smoke Test Conditional(PHNX-6640)

kubernetesV2/PhoenixProductionPipelineTemplateV3.yaml
Motivation
----------
CPU scaling isn't really cutting it for us.
Modifications
-------------
Convert the existing pipeline template to YAML for legibiilty as a
starting point.
Control metric tagging using environment variables across staging, prod,
and prod jobs to ensure it matches with the metric query. Use the
Spinnaker app name as the "app" tag, "production" or "staging" as the
environment, and "api" or "jobs" as the "detail" tag.
Include the DataDog query metric and update the HPA to scale based on
this metric for the prod API and Jobs deploys. Scale the API based on
incoming HTTP requests, and scale the Jobs based on incoming message
queue items being processed.
Introduce new variables which optionally control the scaling thresholds
used for both API and Jobs scaling.
Remove …
=> Create prod pipeline template with metric scaling (PHNX-6702)

kubernetesV2/PhoenixEmergencyPipelineTemplateV3.yaml
Motivation
----------
CPU scaling isn't really cutting it for us.
Modifications
-------------
Port the changes from the V3 prod template to the emergency template.
However, stick with a disabled Docker trigger built into the template
so we can pick any tag instead of picking a specific Jenkins build.
Results
-------
Each microservice may be converted to this template one by one.
https://centeredge.atlassian.net/browse/PHNX-6703
=> Create prod ergemency pipeline temp with metric scaling (PHNX-6703)

kubernetesV2/v4/cleanup.yaml, kubernetesV2/v4/emergency-with-jobs.yaml, kubernetesV2/v4/emergency.yaml, kubernetesV2/v4/production-with-jobs.yaml, kubernetesV2/v4/production.yaml, kubernetesV2/v4/staging.yaml
Motivation
----------
Cleaner and more manageable templates to offload service specifics
to the service's repository.
Modifications
-------------
Implement all new pipeline templates for Kubernetes that keep the same
logical flow but which bake manifests via Kustomize from templates in
the service repository instead of having the manifest within the
template itself.
Also, instead of a "jobsEnabled" variable on the pipeline template,
make two pipeline flavors, with and without jobs.
Instead of triggering cleanup when the production pipeline completes,
include cleanup directly in the production pipeline.
Results
-------
Each service may control its own destiny in production and staging,
rather than all services having identical configurations except where
changed by pipeline template vars …
=> Implement Kustomize pipeline templates (PHNX-7116)

kubernetesV2/PhoenixEmergencyPipelineTemplate.json, kubernetesV2/PhoenixEmergencyPipelineTemplateV3.yaml, kubernetesV2/PhoenixProductionPipelineTemplate.json, kubernetesV2/PhoenixProductionPipelineTemplateV3.yaml, kubernetesV2/PhoenixStagingPipelineTemplate.json
Motivation
----
We are needing to update nginx to allow  for higher upload sizes on membership import endpoints
Modifications
----
* Use Nginx32 with the fix for import endpoints in MashTub
Result
----
Phoenix services should now be using nginx32 which has the changes for higher upload sizes for MashTub membership import endpoints
https://centeredge.atlassian.net/browse/PHNX-7208
=> Update Staging/Production Templates To Nginx32 (PHNX-7208)

kubernetesV2/v4/emergency-with-jobs.yaml, kubernetesV2/v4/emergency.yaml
Motivation
----------
The emergency pipeline deploys are incorrectly requiring smoke test
stages, causing the pipeline to not function.
Modifications
-------------
Remove the offending copy/pasta.
https://centeredge.atlassian.net/browse/PHNX-7547
=> Make emergency pipelines v4 work (PHNX-7547)

kubernetesV2/PhoenixAdvantageProxyPipelineTemplate.yaml
Motivation
----------
Get tracing within the proxy service, and get it to passthrough to
downstream services.
Modifications
-------------
Add the required env vars.
https://centeredge.atlassian.net/browse/ARCH-72
=> Add Jaeger settings to Advantage Proxy (ARCH-72)

kubernetesV2/v4/emergency-with-jobs.yaml, kubernetesV2/v4/emergency.yaml, kubernetesV2/v4/production-with-jobs.yaml, kubernetesV2/v4/production.yaml, kubernetesV2/v4/ui.json
We want to be notified about deploy failures in the Phoenix environment
- Add slack notifications for all production pipelines in the slack channel #phoenixdev-cli
- Add slack notifications for all production pipeline failures, and ALL emergency pipelines in the slack channel #phoenixdev
https://centeredge.atlassian.net/browse/PHNX-10115
=> Add slack notifications to templates (PHNX-10115)

kubernetesV2/PhoenixAdvantageProxyPipelineTemplate.yaml, kubernetesV2/PhoenixEmergencyPipelineTemplate.json, kubernetesV2/PhoenixEmergencyPipelineTemplateV3.yaml, kubernetesV2/PhoenixProductionPipelineTemplate.json, kubernetesV2/PhoenixProductionPipelineTemplateV3.yaml, kubernetesV2/PhoenixUIPipelineTemplate.json
Motivation
----------
K8s version 1.25 removes the v2beta1 version of HorizontalPodAutoscaler
Modifications
-------------
Update the version to v2
https://centeredge.atlassian.net/browse/DO-2018
https://centeredge.atlassian.net/browse/DO-2118
=> Update the HorizontalPodAutoscaler api version (DO-2118)

kubernetesV2/PhoenixEmergencyPipelineTemplate.json, kubernetesV2/PhoenixProductionPipelineTemplate.json, kubernetesV2/PhoenixUIPipelineTemplate.json
Motivation
----------
The targetCPUUtilizationPercentage has been deprecated and needs to be replaced with the metrics block.
Modifications
-------------
Modify the configuration file for the new configuration Also add stabilzation window for HPAs to prevent thrashing
https://centeredge.atlassian.net/browse/DO-2171
=> Fix the Target CPU settings (DO-2171)
